### ISSUE TITLE
Moving folders using EWPtool

### ISSUE THREAD

**Issue by ryoyama1122** [IARSystems/project-migration-tools#12]
I would like to use EWPtool to move a folder on Explorer to another Explorer or workspace.

The following questions are asked in that regard.

After moving (adding) a folder with EWPtool, the folder was not added to the workspace.
In Explorer, the folder was added, but not at the location I wanted.
→How do I add the added folder to the workspace?
　How do I specify the location of the added folder?
 
When I rebuild a folder that was added to the workspace, I get an error message that the path is not followed.
How do I specify the path for each folder?

**Comment by felipe-iar** [comment]
Hi @ryoyama1122,

The __EWPtool__ does not move files around the filesystem. The tool only can scan the selected folders.

According to the instructions in the README.md, it is possible to select more than a single folder to be scanned.
The selected folders (used for re-scan) are saved inside `$PROJ_DIR$\settings\$PROJ_FNAME$.cfg`.
The `.cfg` file can be edited manually if required.

For adding a single file, or a single folder, the standard IDE option might be sufficient. EWPtool was designed to help with multiple folders at once especially when populating a project tree containing multiple folders.

Normally a single group would be created using `Add` > `Add Group...` followed by `Add` > `Add Files...`. the "Add Files..." dialog allows multiple selection as in standard Windows applications (by holding <kbd>CTRL</kbd> and clicking on each desired file, or else by holding <kbd>SHIFT</kbd> and clicking on the first, followed by the last to select multiple files). Dragging'n dropping a selection made from Windows Explorer into a chosen group also works on the latest versions of the IDE.

I hope it helps. Please let me know if you have further questions, otherwise feel free to close this issue.
