### ISSUE TITLE
EWPTool does nothing if project files are in a subfolder

### ISSUE THREAD

**Issue by Steve-Melnikoff** [IARSystems/project-migration-tools#36]
We have a project where the EW project files (e.g. *.eww, *.ewp, *.ewt, etc) are in a subfolder; so if the main project folder is my_project, then these files are in my_project/EWARM.

When EWPTool is run on the project, I can see in the log that it is correctly scanning all the files - but then it stops and exits at the end of the Assembler Header part.

If you move the project files out of the subfolder, the tool works fine! So there is a workaround.

(PS: Thank you for creating this tool. It is incredibly useful, as I find it much easier for the workspace structure in EW to match the actual locations of the files. For one thing, it makes finding files much easier. Using the tool to generate the list of include directories also saves a lot of time.

Are there any plans to incorporate the tool's functionality into EW? I'd also welcome features from Eclipse, like being able to search for files by name, having the workspace explorer automatically open to the currently open file, and having a button to close all open folders in the workspace explorer.)

**Comment by felipe-iar** [comment]
Hi @Steve-Melnikoff,

And your feedback is very welcome and appreciated. Your assertion is correct: while the IAR Engineering team works on a new IDE platform that integrates the EWPtool features, we provide this FAE-led initiative for IAR users. Believe it or not, the tool started as a simple bash script and, thanks to the detailed feedback (and requests) from users like you, we were able to improve its usability over time towards higher productivity.

The scenario you describe resembles pretty much the project style STM32CubeMX generates in which we cover in automated tests before releasing new versions. Can you provide a project in which this issue is reproducible so I can narrow down if it is a defect in the current version? You can archive it as zip it and drop it here if you like. 

> __Suggestion__ In Linux(/WSL) it is possible to quickly create a replica of your project source tree by changing to the topmost project's directory and issuing:
>```
>find -regex ".*.\([ch]p?p?$\|ewp$\|\log$\|cfg$\)" > project.tree.txt`
>```
>Then just zip `project.tree.txt` together with the `*.ewp` and `$PROJ_DIR$/settings/*.{cfg|log}` folder so I can try to reproduce it from my end.
>For EWPtool the only thing that matters is the source tree structure as a whole and I do not expect to build any projects decurrent from the tool's provided detection. If the file names contain sensitive information unsuitable for the public issue tracker, you can reach out to me through felipe.torrezan@iar.com

**Comment by Steve-Melnikoff** [comment]
Hi @felipe-iar; thank you for the quick response.

I have e-mailed you the requested files.

Is there a timescale for the IDE? Also, is there a preferred route for providing feedback and suggestions?

Many thanks.

**Comment by felipe-iar** [comment]
Hi Steve and thanks for reporting. Though I was unable to reproduce from my end as we discussed via email. Please feel free to reopen at anytime if needed.
